name: autolume
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - aom=3.9.1=he0c23c2_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.9.24=haa95532_0
  - cairo=1.18.0=h32b962e_3
  - dav1d=1.2.1=hcfcfb64_0
  - expat=2.6.3=he0c23c2_0
  - ffmpeg=7.1.0=gpl_hb26d62f_701
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=hdaf720e_2
  - graphite2=1.3.13=h63175ca_1003
  - harfbuzz=9.0.0=h2bedf89_1
  - icu=75.1=he0c23c2_0
  - libexpat=2.6.3=he0c23c2_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.82.1=h7025463_0
  - libiconv=1.17=hcfcfb64_2
  - libintl=0.22.5=h5728263_3
  - libopus=1.3.1=h8ffe710_1
  - libpng=1.6.44=h3ca93ac_0
  - libsqlite=3.46.1=h2466b09_0
  - libxml2=2.12.7=h0f24e4e_4
  - libzlib=1.3.1=h2466b09_2
  - openh264=2.4.1=h63175ca_0
  - openssl=3.3.2=h2466b09_0
  - pcre2=10.44=h3d7b363_2
  - pip=24.2=py310haa95532_0
  - pixman=0.43.4=h63175ca_0
  - python=3.10.15=hfaddaf0_1_cpython
  - sqlite=3.45.3=h2bbff1b_0
  - svt-av1=2.2.1=he0c23c2_0
  - tk=8.6.13=h5226925_1
  - ucrt=10.0.22621.0=h57928b3_1
  - vc=14.40=h2eaa2aa_1
  - vc14_runtime=14.40.33810=hcc2c482_22
  - vs2015_runtime=14.40.33810=h3bf8584_22
  - wheel=0.44.0=py310haa95532_0
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xz=5.4.6=h8cc25b3_1
  - zlib=1.3.1=h2466b09_2
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - altgraph==0.17.4
      - audioread==3.0.1
      - certifi==2022.12.7
      - cffi==1.16.0
      - charset-normalizer==2.1.1
      - click==8.1.7
      - openai-clip==1.0.1
      - colorama==0.4.6
      - contourpy==1.1.1
      - cycler==0.12.1
      - datetime==5.5
      - decorator==4.4.2
      - fbpca==1.0
      - ffmpeg-python==0.2.0
      - filelock==3.9.0
      - fonttools==4.43.1
      - fsspec==2024.9.0
      - ftfy==6.1.1
      - future==0.18.3
      - glfw==2.6.2
      - idna==3.4
      - imageio==2.31.5
      - imageio-ffmpeg==0.4.9
      - imgui==1.4.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - kmeans-pytorch==0.3
      - kornia==0.7.0
      - lazy-loader==0.3
      - librosa==0.10.1
      - llvmlite==0.41.1
      - lmdb==1.5.1
      - lpips==0.1.4
      - markupsafe==2.1.2
      - matplotlib==3.8.0
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.0.7
      - ndi-python==5.1.1.1
      - networkx==3.0
      - ninja==1.11.1.1
      - numba==0.58.1
      - numpy==1.26.4
      - nvidia-pyindex==1.0.9
      - opencv-python==4.8.1.78
      - opensimplex==0.4.5
      - packaging==23.2
      - pandas==2.1.1
      - pefile==2024.8.26
      - pillow==9.3.0
      - platformdirs==3.11.0
      - pooch==1.7.0
      - proglog==0.1.10
      - psutil==5.9.6
      - pyaudio==0.2.13
      - pycparser==2.21
      - pyinstaller==6.10.0
      - pyinstaller-hooks-contrib==2024.8
      - pyopengl==3.1.7
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-osc==1.8.3
      - pytz==2023.3.post1
      - pywin32-ctypes==0.2.3
      - pyyaml==6.0.1
      - regex==2023.10.3
      - requests==2.28.1
      - scikit-image==0.22.0
      - scikit-learn==1.3.1
      - scipy==1.11.3
      - seaborn==0.13.0
      - setuptools==58.0.0
      - six==1.16.0
      - soundfile==0.12.1
      - soxr==0.3.7
      - termcolor==2.3.0
      - threadpoolctl==3.2.0
      - tifffile==2023.9.26
      - timm==0.5.4
      - torch==2.8.0+cu128
      - torchaudio==2.8.0+cu128
      - torchvision==0.23.0+cu128
      - tqdm==4.66.1
      - tzdata==2023.3
      - urllib3==1.26.13
      - visualizer==0.0.10
      - wcwidth==0.2.8
      - wordcloud==1.9.2
      - zope-interface==7.0.3