site_name: Autolume - Documentation
repo_name: Metacreation-Lab/autolume
repo_url: https://github.com/Metacreation-Lab/autolume
theme:
  name: material
  favicon: assets/logo.webp
  logo: assets/logo.webp
  features:
    - navigation.footer
  palette:
    primary: custom
    accent: custom
extra_css:
  - assets/extra.css